[package]
name = "area-lut"
version = "0.2.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
clap = "2.30"
euclid = "0.20"

[dependencies.image]
version = "0.23"
default-features = false
features = ["png"]
