[package]
name = "generate-gamma-lut"
version = "0.1.0"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]

[dependencies]
clap = "2.27"
log = "0.4"

[dependencies.image]
version = "0.23"
default-features = false
features = ["png"]
